# This file is just for installing deps;
# TODO move to `dune pkg`.

opam-version: "2.0"
maintainer: "Nandakumar Edamana <nandakumar@nandakumar.co.in>"
synopsis: "Tnum Arithmetic Verified in Rocq"

depends: [
	"rocq-core" {>= "9.1"}
	"dune" {>= "3.21"}
	# NONFREE "coq-compcert" {>= "3.17"}
	# NEEDSCOMPCERT "coq-vst" {>= "2.16"}
]

build: [
	["dune" "build"]
]
