(rule
 (targets tnumSplitDotC.v)
 (deps tnum-split.c Makefile)
 (action (run make tnumSplitDotC.v))
)

(rocq.theory
 (name trirocq.Verification)
 (theories trirocq VST Flocq)
 ; putting compcert above along VST doesn't work
 ; for the coq-compcert opam package; layout issue?
 (flags -Q %{env:OPAM_SWITCH_PREFIX=}/lib/coq/user-contrib/compcert compcert)
)
