Require Import trirocq.Bit.
Require Import trirocq.BitVector.
Require Import trirocq.Tnum.
Require Import trirocq.TnumAdd.

Section linux_tnum_subtraction.
  (* Mirrors the Linux kernel definition *)

  Definition tnum_sub_ith_chi {SIZE} P Q [i] (hidx : i < SIZE) :=
    let dv := bvec_sub (tnum.v P) (tnum.v Q) in
    let alpha := bvec_add dv (tnum.m P) in
    let beta := bvec_sub dv (tnum.m Q) in
    let chi := bvec_xor alpha beta in
    bvec_ith chi hidx.

  Definition tnum_sub {SIZE} P Q :=
    let dv := bvec_sub (tnum.v P) (tnum.v Q) in
    let alpha := bvec_add dv (tnum.m P) in
    let beta := bvec_sub dv (tnum.m Q) in
    let chi := bvec_xor alpha beta in
    let mu := bvec_or chi (bvec_or (tnum.m P) (tnum.m Q)) in
    tnum.cons SIZE (bvec_and dv (bvec_neg mu)) mu.

  Lemma sublemma32 {SIZE} P Q :
    tnum.wellformed P -> tnum.wellformed Q ->
    forall [i] (hidx : i < SIZE),
      tnum.ith_m (tnum_sub P Q) hidx = zero ->
      tnum.ith_m P hidx = zero /\ tnum.ith_m Q hidx = zero /\
        tnum_sub_ith_chi P Q hidx = zero.
  Proof.
    unfold tnum.wellformed. unfold tnum_sub_ith_chi.
    intros wf1 wf2 i hidx.
    specialize (wf1 i hidx).
    specialize (wf2 i hidx).

    destruct i;
      unfold tnum_sub;
      rewrite tnum.ith_m_simplify;
      unwrap_bvec_ops; unfold tnum.ith_m;
      rewrite bvec_fullsub_result;
      unfold bvec_inborrow;
      crush_bvec_add.
  Qed.

  Lemma xor_x_y_eq_z_y x y z : bit_xor x y = bit_xor z y -> x = z.
    unfold bit_xor; destruct x; destruct y; destruct z; try easy.
  Qed.

  Ltac easy_neg :=
    let H := fresh "H" in
    match goal with
    | [ |- ?x = bit_not ?x -> _ ] => unfold bit_not; easy
    end.

  (* concerns the borrows generated by dv and beta *)
  Lemma sublemma64 {SIZE} P Q :
    tnum.wellformed P -> tnum.wellformed Q ->
    forall [i] (hidx : i < SIZE),
      bit_and (bvec_inborrow (tnum.v P) (tnum.v Q) hidx)
        (bvec_inborrow (bvec_sub (tnum.v P) (tnum.v Q)) (tnum.m Q) hidx) = zero.
  Proof.
    unfold tnum.wellformed. unfold ingamma.
    unfold tnum.ith_m. unfold tnum.ith_v.
    intros wfp wfq.
    induction i.
    - auto.
    -
      intros hidx.

      specialize (IHi (ltprv hidx)).
      specialize_wf_ig (ltprv hidx).

      repeat rewrite bvec_inborrow_Si. simpl.
      repeat rewrite bvec_fullsub_result. simpl.
      crush_bvec_add.
  Qed.

  (* TODO fuse with sublemma64? *)
  (* concerns the borrow generated by dv and the carry generated by alpha *)
  Lemma sublemma67 {SIZE} P Q :
    tnum.wellformed P -> tnum.wellformed Q ->
    forall [i] (hidx : i < SIZE),
      bvec_inborrow (tnum.v P) (tnum.v Q) hidx = zero ->
        bvec_incarry (bvec_sub (tnum.v P) (tnum.v Q)) (tnum.m P) hidx = zero.
  Proof.
    unfold tnum.wellformed. unfold ingamma.
    unfold tnum.ith_m. unfold tnum.ith_v.
    intros wfp wfq.
    induction i.
    - intro. repeat rewrite bvec_incarry_0. auto.
    - simpl.
      intros hidx.

      specialize (IHi (ltprv hidx)).
      specialize_wf_ig (ltprv hidx).

      repeat rewrite bvec_incarry_Si. repeat rewrite bvec_inborrow_Si. simpl.
      repeat rewrite bvec_fullsub_result. simpl.

      crush_bvec_add.
  Qed.

  Lemma sublemma42 {SIZE} P Q :
    forall [i] (hidx : S i < SIZE),
      bvec_incarry (tnum.m P) (tnum.m Q) hidx = zero ->
      bit_and (bvec_ith (tnum.m P) (ltprv hidx)) (bvec_ith (tnum.m Q) (ltprv hidx)) = zero.
  Proof.
    unfold tnum.wellformed.
    intros i hidx.
    rewrite bvec_incarry_Si.
    crush_bvec_add.
  Qed.

  Lemma sublemma43 {SIZE} P Q :
    tnum.wellformed P -> tnum.wellformed Q ->
    forall [i] (hidx : i < SIZE),
      bvec_incarry (bvec_sub (tnum.v P) (tnum.v Q)) (tnum.m P) hidx =
        bvec_inborrow (bvec_sub (tnum.v P) (tnum.v Q)) (tnum.m Q) hidx ->
      bvec_incarry (tnum.m P) (tnum.m Q) hidx = zero.
  Proof.
    unfold tnum.wellformed. unfold ingamma.
    unfold tnum.ith_m. unfold tnum.ith_v.
    intros wfp wfq.
    induction i.
    - intro. repeat rewrite bvec_incarry_0. auto.
    -
      intro hidx.

      assert (h64 := sublemma64 P Q wfp wfq (ltprv hidx)).
      assert (h67 := sublemma67 P Q wfp wfq (ltprv hidx)).

      specialize (IHi (ltprv hidx)).
      specialize_wf_ig (ltprv hidx).

      repeat rewrite bvec_incarry_Si.
      simpl.
      repeat rewrite bvec_fullsub_result. simpl.

      crush_bvec_add.
  Qed.

  (* Turns out inborrow = incarry if the result has mask = 0. *)
  Lemma sublemma45 {SIZE} x y P Q :
    tnum.wellformed P -> tnum.wellformed Q -> ingamma x P -> ingamma y Q ->
    forall [i] (hidx : i < SIZE),
      bvec_incarry (bvec_sub (tnum.v P) (tnum.v Q)) (tnum.m P) hidx =
        bvec_inborrow (bvec_sub (tnum.v P) (tnum.v Q)) (tnum.m Q) hidx ->
      bvec_inborrow x y hidx = bvec_inborrow (tnum.v P) (tnum.v Q) hidx.
  Proof.
    unfold tnum.wellformed. unfold ingamma.
    unfold tnum.ith_m. unfold tnum.ith_v.
    intros wfp wfq igP igQ.
    induction i.
    - unfold bvec_inborrow. auto.
    -
      intro hidx.

      intro H.
      (* Not true for borrow. TODO note: why is this the case? Consider the case of `mu - mu`; `P.mask - Q.mask` = `1 - 1 = 0`, no borrow; but the uncertainty should actually propagate; hence carry. *)
      assert (h43 := sublemma43 P Q wfp wfq hidx).
      revert H. revert h43.
      intro H.

      assert (h64 := sublemma64 P Q wfp wfq (ltprv hidx)).
      assert (h67 := sublemma67 P Q wfp wfq (ltprv hidx)).

      repeat rewrite bvec_incarry_Si.
      repeat rewrite bvec_inborrow_Si.
      repeat rewrite bvec_fullsub_result. simpl.

      specialize (IHi (ltprv hidx)).
      pose (hspec := specialize_wf_ig wfp wfq igP igQ (ltprv hidx)).
      destruct hspec as (wfps & wfqs & igps & igqs).

      crush_bvec_add.
  Qed.

  Lemma sublemma33 {SIZE} x y P Q :
    tnum.wellformed P -> tnum.wellformed Q -> ingamma x P -> ingamma y Q ->
    forall [i] (hidx : i < SIZE),
      tnum.ith_m (tnum_sub P Q) hidx = zero ->
      bvec_inborrow x y hidx = bvec_inborrow (tnum.v P) (tnum.v Q) hidx.
  Proof.
    unfold tnum.wellformed. unfold ingamma.
    unfold tnum.ith_m. unfold tnum.ith_v.
    intros wfp wfq igP igQ.
    induction i.
    - unfold bvec_inborrow. auto.
    -
      intros hidx.
      unfold tnum_sub.
      rewrite tnum.ith_m_simplify2.
      unwrap_bvec_ops.
      repeat rewrite bvec_fulladd_result. repeat rewrite bvec_fullsub_result.

      (* TODO why don't reuse sublemma32 here? If doing, do the same for addition as well. *)

      intro H.
      assert (hmp : bvec_ith (tnum.m P) hidx = zero). revert H.
      destruct (bvec_ith (tnum.m P) hidx);
        repeat simplify_bit_ops; try easy.

      assert (hmq : bvec_ith (tnum.m Q) hidx = zero). revert H.
      destruct (bvec_ith (tnum.m Q) hidx);
        repeat simplify_bit_ops; try easy.

      simplify_bit_ops.
      apply bit_or_zero_zero in H as (H1 & H2).
      apply bit_xor_x_y_zero in H1.

      rewrite hmp in H1. rewrite hmq in H1.
      apply xor_x_y_eq_z_y in H1.

      (* H1 seems interesting at this point:
         bvec_incarry (bvec_sub (tnum.v P) (tnum.v Q)) (tnum.m P) hidx =
         bvec_inborrow (bvec_sub (tnum.v P) (tnum.v Q)) (tnum.m Q) hidx
       *)
      apply sublemma45; auto.
  Qed.

  Lemma tnum_sub_wellformed {SIZE} (P Q : tnum.t SIZE) :
    tnum.wellformed P /\ tnum.wellformed Q -> tnum.wellformed (tnum_sub P Q).
  Proof.
    unfold tnum.wellformed.
    intro H.
    unfold tnum_sub.
    apply wellformed_general.
  Qed.

  Ltac unfold_tnum_goodies :=
    unfold tnum.wellformed; unfold ingamma;
    unfold tnum_sub_ith_chi;
    unfold tnum.ith_m; unfold tnum.ith_v.

  Lemma tnum_sub_sound {SIZE} x y (P Q : tnum.t SIZE) :
    tnum.wellformed P /\ tnum.wellformed Q /\ ingamma x P /\ ingamma y Q ->
    tnum.wellformed (tnum_sub P Q) /\
      ingamma (bvec_sub x y) (tnum_sub P Q).
  Proof.
    unfold_tnum_goodies.
    intros H. destruct H as (wfp & wfq & igP & igQ).

    split. apply tnum_sub_wellformed; auto.

    intros i hidx rmskz.

    assert (H33 := sublemma33 x y P Q wfp wfq igP igQ hidx rmskz).
    assert (H32 := sublemma32 P Q wfp wfq hidx rmskz).
    revert H32 H33. unfold_tnum_goodies. intros H32 H33.

    destruct H32 as (xmskz & ymskz & cinmskz).
    revert cinmskz rmskz.

    unfold tnum_sub.
    rewrite tnum.ith_m_simplify2.
    rewrite tnum.ith_v_simplify2.

    unwrap_bvec_ops. repeat rewrite bvec_fullsub_result.
    rewrite xmskz. rewrite ymskz. rewrite igP; auto. rewrite igQ; auto. simpl.

    intros H1 H2.

    rewrite H2. simpl.
    rewrite H33.
    rewrite bit_and_right_one.
    auto.
  Qed.
End linux_tnum_subtraction.
