Require Import trirocq.Bit.
Require Import trirocq.BitSub.
Require Import trirocq.BitVector.
Require Import trirocq.SigVector.
Require Import trirocq.Tnum.
Require Import trirocq.TnumAdd.

From Stdlib Require Import Lia.
From Stdlib Require Import ZArith.
From Stdlib Require Import ZArithRing.

Section linux_tnum_subtraction.
  (* Mirrors the Linux kernel definition *)

  Definition tnum_sub_ith_chi {SIZE} P Q [i] (hidx : i < SIZE) :=
    let dv := bvec_sub (tnum.v P) (tnum.v Q) in
    let alpha := bvec_add dv (tnum.m P) in
    let beta := bvec_sub dv (tnum.m Q) in
    let chi := bvec_xor alpha beta in
    bvec_ith chi hidx.

  Definition tnum_sub {SIZE} P Q :=
    let dv := bvec_sub (tnum.v P) (tnum.v Q) in
    let alpha := bvec_add dv (tnum.m P) in
    let beta := bvec_sub dv (tnum.m Q) in
    let chi := bvec_xor alpha beta in
    let mu := bvec_or chi (bvec_or (tnum.m P) (tnum.m Q)) in
    tnum.cons SIZE (bvec_and dv (bvec_neg mu)) mu.

  Lemma sublemma32 {SIZE} P Q :
    tnum.wellformed P -> tnum.wellformed Q ->
    forall [i] (hidx : i < SIZE),
      tnum.ith_m (tnum_sub P Q) hidx = zero ->
      tnum.ith_m P hidx = zero /\ tnum.ith_m Q hidx = zero /\
        tnum_sub_ith_chi P Q hidx = zero.
  Proof.
    unfold tnum.wellformed. unfold tnum_sub_ith_chi.
    intros wf1 wf2 i hidx.
    specialize (wf1 i hidx).
    specialize (wf2 i hidx).

    destruct i;
      unfold tnum_sub;
      rewrite tnum.ith_m_simplify;
      unwrap_bvec_ops; unfold tnum.ith_m;
      rewrite bvec_fullsub_result;
      unfold bvec_inborrow;
      crush_bvec_add.
  Qed.

  Lemma xor_x_y_eq_z_y x y z : bit_xor x y = bit_xor z y -> x = z.
    unfold bit_xor; destruct x; destruct y; destruct z; try easy.
  Qed.

  Ltac easy_neg :=
    let H := fresh "H" in
    match goal with
    | [ |- ?x = bit_not ?x -> _ ] => unfold bit_not; easy
    end.

  (* concerns the borrows generated by dv and beta *)
  Lemma sublemma64 {SIZE} P Q :
    tnum.wellformed P -> tnum.wellformed Q ->
    forall [i] (hidx : i < SIZE),
      bit_and (bvec_inborrow (tnum.v P) (tnum.v Q) hidx)
        (bvec_inborrow (bvec_sub (tnum.v P) (tnum.v Q)) (tnum.m Q) hidx) = zero.
  Proof.
    unfold tnum.wellformed. unfold ingamma.
    unfold tnum.ith_m. unfold tnum.ith_v.
    intros wfp wfq.
    induction i.
    - intros. rewrite bvec_inborrow_0. auto.
    -
      intros hidx.

      specialize (IHi (ltprv hidx)).
      specialize_wf_ig (ltprv hidx).

      repeat rewrite bvec_inborrow_Si. simpl.
      repeat rewrite bvec_fullsub_result. simpl.
      crush_bvec_add.
  Qed.

  (* TODO fuse with sublemma64? *)
  (* concerns the borrow generated by dv and the carry generated by alpha *)
  Lemma sublemma67 {SIZE} P Q :
    tnum.wellformed P -> tnum.wellformed Q ->
    forall [i] (hidx : i < SIZE),
      bvec_inborrow (tnum.v P) (tnum.v Q) hidx = zero ->
      bvec_incarry (bvec_sub (tnum.v P) (tnum.v Q)) (tnum.m P) hidx = zero.
  Proof.
    unfold tnum.wellformed. unfold ingamma.
    unfold tnum.ith_m. unfold tnum.ith_v.
    intros wfp wfq.
    induction i.
    - intro. repeat rewrite bvec_incarry_0. auto.
    - simpl.
      intros hidx.

      specialize (IHi (ltprv hidx)).
      specialize_wf_ig (ltprv hidx).

      repeat rewrite bvec_incarry_Si. repeat rewrite bvec_inborrow_Si. simpl.
      repeat rewrite bvec_fullsub_result. simpl.

      crush_bvec_add.
  Qed.

  Lemma sublemma42 {SIZE} P Q :
    forall [i] (hidx : S i < SIZE),
      bvec_incarry (tnum.m P) (tnum.m Q) hidx = zero ->
      bit_and (bvec_ith (tnum.m P) (ltprv hidx)) (bvec_ith (tnum.m Q) (ltprv hidx)) = zero.
  Proof.
    unfold tnum.wellformed.
    intros i hidx.
    rewrite bvec_incarry_Si.
    crush_bvec_add.
  Qed.

  Lemma sublemma43 {SIZE} P Q :
    tnum.wellformed P -> tnum.wellformed Q ->
    forall [i] (hidx : i < SIZE),
      bvec_incarry (bvec_sub (tnum.v P) (tnum.v Q)) (tnum.m P) hidx =
        bvec_inborrow (bvec_sub (tnum.v P) (tnum.v Q)) (tnum.m Q) hidx ->
      bvec_incarry (tnum.m P) (tnum.m Q) hidx = zero.
  Proof.
    unfold tnum.wellformed. unfold ingamma.
    unfold tnum.ith_m. unfold tnum.ith_v.
    intros wfp wfq.
    induction i.
    - intro. repeat rewrite bvec_incarry_0. auto.
    -
      intro hidx.

      assert (h64 := sublemma64 P Q wfp wfq (ltprv hidx)).
      assert (h67 := sublemma67 P Q wfp wfq (ltprv hidx)).

      specialize (IHi (ltprv hidx)).
      specialize_wf_ig (ltprv hidx).

      repeat rewrite bvec_incarry_Si. simpl.
      repeat rewrite bvec_inborrow_Si. simpl.
      repeat rewrite bvec_fullsub_result. simpl.

      crush_bvec_add.
  Qed.

  (* Turns out inborrow = incarry if the result has mask = 0. *)
  Lemma sublemma45 {SIZE} x y P Q :
    tnum.wellformed P -> tnum.wellformed Q -> ingamma x P -> ingamma y Q ->
    forall [i] (hidx : i < SIZE),
      bvec_incarry (bvec_sub (tnum.v P) (tnum.v Q)) (tnum.m P) hidx =
        bvec_inborrow (bvec_sub (tnum.v P) (tnum.v Q)) (tnum.m Q) hidx ->
      bvec_inborrow x y hidx = bvec_inborrow (tnum.v P) (tnum.v Q) hidx.
  Proof.
    unfold tnum.wellformed. unfold ingamma.
    unfold tnum.ith_m. unfold tnum.ith_v.
    intros wfp wfq igP igQ.
    induction i.
    - intros. repeat rewrite bvec_inborrow_0. auto.
    -
      intro hidx.

      intro H.
      (* Not true for borrow. TODO note: why is this the case? Consider the case of `mu - mu`; `P.mask - Q.mask` = `1 - 1 = 0`, no borrow; but the uncertainty should actually propagate; hence carry. *)
      assert (h43 := sublemma43 P Q wfp wfq hidx).
      revert H. revert h43.
      intro H.

      assert (h64 := sublemma64 P Q wfp wfq (ltprv hidx)).
      assert (h67 := sublemma67 P Q wfp wfq (ltprv hidx)).

      repeat rewrite bvec_incarry_Si.
      repeat rewrite bvec_inborrow_Si.
      repeat rewrite bvec_fullsub_result. simpl.

      specialize (IHi (ltprv hidx)).
      pose (hspec := specialize_wf_ig wfp wfq igP igQ (ltprv hidx)).
      destruct hspec as (wfps & wfqs & igps & igqs).

      crush_bvec_add.
  Qed.

  Lemma sublemma33 {SIZE} x y P Q :
    tnum.wellformed P -> tnum.wellformed Q -> ingamma x P -> ingamma y Q ->
    forall [i] (hidx : i < SIZE),
      tnum.ith_m (tnum_sub P Q) hidx = zero ->
      bvec_inborrow x y hidx = bvec_inborrow (tnum.v P) (tnum.v Q) hidx.
  Proof.
    unfold tnum.wellformed. unfold ingamma.
    unfold tnum.ith_m. unfold tnum.ith_v.
    intros wfp wfq igP igQ.
    induction i.
    - intros. repeat rewrite bvec_inborrow_0. auto.
    -
      intros hidx.
      unfold tnum_sub.
      rewrite tnum.ith_m_simplify2.
      unwrap_bvec_ops.
      repeat rewrite bvec_fulladd_result. repeat rewrite bvec_fullsub_result.

      (* TODO why don't reuse sublemma32 here? If doing, do the same for addition as well. *)

      intro H.
      assert (hmp : bvec_ith (tnum.m P) hidx = zero). revert H.
      destruct (bvec_ith (tnum.m P) hidx);
        repeat simplify_bit_ops; try easy.

      assert (hmq : bvec_ith (tnum.m Q) hidx = zero). revert H.
      destruct (bvec_ith (tnum.m Q) hidx);
        repeat simplify_bit_ops; try easy.

      simplify_bit_ops.
      apply bit_or_zero_zero in H as (H1 & H2).
      apply bit_xor_x_y_zero in H1.

      rewrite hmp in H1. rewrite hmq in H1.
      apply xor_x_y_eq_z_y in H1.

      (* H1 seems interesting at this point:
         bvec_incarry (bvec_sub (tnum.v P) (tnum.v Q)) (tnum.m P) hidx =
         bvec_inborrow (bvec_sub (tnum.v P) (tnum.v Q)) (tnum.m Q) hidx
       *)
      apply sublemma45; auto.
  Qed.

  Lemma tnum_sub_wellformed {SIZE} (P Q : tnum.t SIZE) :
    tnum.wellformed P /\ tnum.wellformed Q -> tnum.wellformed (tnum_sub P Q).
  Proof.
    unfold tnum.wellformed.
    intro H.
    unfold tnum_sub.
    apply wellformed_general.
  Qed.

  Ltac unfold_tnum_goodies :=
    unfold tnum.wellformed; unfold ingamma;
    unfold tnum_sub_ith_chi;
    unfold tnum.ith_m; unfold tnum.ith_v.

  Lemma tnum_sub_sound {SIZE} x y (P Q : tnum.t SIZE) :
    tnum.wellformed P /\ tnum.wellformed Q /\ ingamma x P /\ ingamma y Q ->
    tnum.wellformed (tnum_sub P Q) /\
      ingamma (bvec_sub x y) (tnum_sub P Q).
  Proof.
    unfold_tnum_goodies.
    intros H. destruct H as (wfp & wfq & igP & igQ).

    split. apply tnum_sub_wellformed; auto.

    intros i hidx rmskz.

    assert (H33 := sublemma33 x y P Q wfp wfq igP igQ hidx rmskz).
    assert (H32 := sublemma32 P Q wfp wfq hidx rmskz).
    revert H32 H33. unfold_tnum_goodies. intros H32 H33.

    destruct H32 as (xmskz & ymskz & cinmskz).
    revert cinmskz rmskz.

    unfold tnum_sub.
    rewrite tnum.ith_m_simplify2.
    rewrite tnum.ith_v_simplify2.

    unwrap_bvec_ops. repeat rewrite bvec_fullsub_result.
    rewrite xmskz. rewrite ymskz. rewrite igP; auto. rewrite igQ; auto. simpl.

    intros H1 H2.

    rewrite H2. simpl.
    rewrite H33.
    rewrite bit_and_right_one.
    auto.
  Qed.

  Section tnum_sub_optimality.
    Lemma tnum_sub_mu_imp_inputs_mu {SIZE} P Q :
      forall [i] (hidx : i < SIZE),
        tnum.ith_m (tnum_sub P Q) hidx = one ->
        tnum.ith_m P hidx = one \/ tnum.ith_m Q hidx = one \/
          tnum_sub_ith_chi P Q hidx = one.
    Proof.
      unfold_tnum_goodies.
      intros i hidx.

      destruct i;
        unfold tnum_sub;
        rewrite tnum.ith_m_simplify2;
        unwrap_bvec_ops; unfold tnum.ith_m;
        rewrite bvec_fulladd_result;
        unfold bvec_incarry;
        repeat destruct (bvec_ith (tnum.m _) hidx); try auto;
        repeat simplify_bit_ops; try auto.
    Qed.

    Lemma bvec_ith_set_prv_borrow_intact {SIZE} (x y : bvec SIZE) i (hi : i < SIZE) j (hj : j < SIZE) :
      j < i ->
      bvec_inborrow x y hj = bvec_inborrow (BitVector.bvec_set_ith x hi) y hj.
    Proof.
      induction j.
      - repeat rewrite bvec_inborrow_0. auto.
      - repeat rewrite bvec_inborrow_Si.

        intro sjlti. assert (j < i). lia.

        rewrite bvec_ith_unset_is_id.
        rewrite IHj.
        auto. auto. lia.
    Qed.

    Lemma bvec_ith_set_prv_borrow_intact_rev {SIZE} (x y : bvec SIZE) i (hi : i < SIZE) j (hj : j < SIZE) :
      j < i ->
      bvec_inborrow x y hj = bvec_inborrow x (BitVector.bvec_set_ith y hi) hj.
    Proof.
      induction j.
      - repeat rewrite bvec_inborrow_0. auto.
      - repeat rewrite bvec_inborrow_Si.

        intro sjlti. assert (j < i). lia.

        rewrite bvec_ith_unset_is_id.
        rewrite IHj.
        auto. auto. lia.
    Qed.

    Lemma bvec_ith_set_sets_ith_diff {SIZE} (x y : bvec SIZE) i (hidx : i < SIZE) :
      bvec_ith x hidx = zero ->
      bvec_ith (bvec_sub x y) hidx <>
        bvec_ith (bvec_sub (BitVector.bvec_set_ith x hidx) y) hidx.
    Proof.
      repeat rewrite bvec_fullsub_result.
      destruct i.
      - repeat rewrite bvec_incarry_0.
        rewrite bvec_ith_set_is_one.
        simplify_bit_ops.
        repeat rewrite bvec_inborrow_0.
        repeat destruct (bvec_ith _ _); easy.
      - repeat rewrite bvec_inborrow_Si. simpl.
        rewrite bvec_ith_unset_is_id; auto.
        rewrite bvec_ith_set_is_one.
        rewrite bvec_ith_set_prv_borrow_intact with (hi := hidx); auto.

        repeat destruct (bvec_ith _ _);
          destruct (bvec_inborrow _ _ _); simplify_bit_ops; discriminate.
    Qed.

    (* Can't reuse bvec_ith_set_sets_ith_diff unlike in the case of
     * bvec_add because bvec_sub is not commutative.
     *)
    Lemma bvec_ith_set_sets_ith_diff_rev {SIZE} (x y : bvec SIZE) i (hidx : i < SIZE) :
      bvec_ith y hidx = zero ->
      bvec_ith (bvec_sub x y) hidx <>
        bvec_ith (bvec_sub x (BitVector.bvec_set_ith y hidx)) hidx.
    Proof.
      repeat rewrite bvec_fullsub_result.
      destruct i.
      - repeat rewrite bvec_inborrow_0.
        rewrite bvec_ith_set_is_one.
        simplify_bit_ops.
        repeat destruct (bvec_ith _ _); easy.
      - repeat rewrite bvec_inborrow_Si. simpl.
        rewrite bvec_ith_unset_is_id; auto.
        rewrite bvec_ith_set_is_one.
        rewrite bvec_ith_set_prv_borrow_intact_rev with (hi := hidx); auto.

        repeat destruct (bvec_ith _ _);
          destruct (bvec_inborrow _ _ _); simplify_bit_ops; discriminate.
    Qed.

    (* If the abstract result indicates uncertainty at some bit, there
     * should be concrete diffs with mismatching bits at that position.
     * Note: Either p <> p' or q <> q' should hold, but both need not.
     *)
    Lemma tnum_sub_optimal : forall [n] P Q i (hidx : i < S n),
        tnum.wellformed P -> tnum.wellformed Q ->
        tnum.ith_m (tnum_sub P Q) hidx = one ->
        exists p q p' q',
          ingamma p P /\ ingamma q Q /\
            ingamma p' P /\ ingamma q' Q /\
            bvec_ith (bvec_sub p q) hidx <> bvec_ith (bvec_sub p' q') hidx.
    Proof.
      intros SIZE P Q i hidx wfp wfq sum_mu.
      apply (tnum_sub_mu_imp_inputs_mu P Q) in sum_mu.

      destruct sum_mu as [ pm | [ qm | chim ] ].
      - exists (tnum.v P), (tnum.v Q).
        exists (BitVector.bvec_set_ith (tnum.v P) hidx), (tnum.v Q).
        repeat split.
        + apply tnum_ingamma_set_at_mask; auto.
        + apply bvec_ith_set_sets_ith_diff. auto.

      - exists (tnum.v P), (tnum.v Q).
        exists (tnum.v P), (BitVector.bvec_set_ith (tnum.v Q) hidx).
        repeat split.
        + apply tnum_ingamma_set_at_mask; auto.
        + apply bvec_ith_set_sets_ith_diff_rev. auto.

      - unfold tnum_sub_ith_chi in chim.
        revert chim.

        unwrap_bvec_ops.

        Local Open Scope Z_scope.
        assert (hassoc1Z : forall x y z : Z, (x - y) + z = (x + z) - y). lia.

        assert (hassoc1 : forall n (x y z : bvec (S n)),
                   bvec_add (bvec_sub x y) z = bvec_sub (bvec_add x z) y).
        intros n' x y z.
        apply eqdenote_imp_eqvec.
        apply Nat2Z.inj.
        rewrite bvec_add_correct_Z.
        repeat rewrite bvec_sub_correct_Z.
        rewrite bvec_add_correct_Z.
        rewrite Z.add_mod_idemp_l by lia.
        rewrite Zminus_mod_idemp_l.
        f_equal. lia.
        rewrite hassoc1.

        assert (hassoc2 : forall n (x y z : bvec (S n)),
                   bvec_sub (bvec_sub x y) z = bvec_sub x (bvec_add y z)).
        intros n' x y z. apply eqdenote_imp_eqvec.
        apply Nat2Z.inj.
        repeat rewrite bvec_sub_correct_Z.
        rewrite bvec_add_correct_Z.
        rewrite Zminus_mod_idemp_l.
        rewrite Zminus_mod_idemp_r.
        f_equal. lia.
        rewrite hassoc2.
        Close Scope Z_scope.

        repeat rewrite <- tnum_add_v_m_is_or; auto.

        intro chim.
        apply bit_xor_one_imp in chim.
        destruct (bvec_ith (bvec_sub (bvec_or (tnum.v P) (tnum.m P)) (tnum.v Q)) hidx) eqn : hvm;
          simplify_bit_ops;
          revert chim; simplify_bit_ops.
        +
          (* We have:
           * 1) bvec_ith (bvec_sub (bvec_or (tnum.v P) (tnum.m P)) (tnum.v Q)) hidx = zero
           * 2) bvec_ith (bvec_sub (tnum.v P) (bvec_or (tnum.v Q) (tnum.m Q))) hidx = one
           * i.e., (Pmax - Qmin)[i] = 0 and (Pmin - Qmax)[i] = 1.
           *)

          exists (bvec_or (tnum.v P) (tnum.m P)). (* p *)
          exists (tnum.v Q). (* q *)
          exists (tnum.v P). (* p' *)
          exists (bvec_or (tnum.v Q) (tnum.m Q)). (* q' *)

          repeat split.
          * apply ingamma_value_bitor_mask.
          * apply ingamma_value_bitor_mask.
          * destruct chim as (h1 & h2).
            rewrite hvm, h1.
            discriminate.
        +
          exists (bvec_or (tnum.v P) (tnum.m P)). (* p *)
          exists (tnum.v Q). (* q *)
          exists (tnum.v P). (* p' *)
          exists (bvec_or (tnum.v Q) (tnum.m Q)). (* q' *)

          repeat split.
          * apply ingamma_value_bitor_mask.
          * apply ingamma_value_bitor_mask.
          * destruct chim as (h1 & h2).
            rewrite hvm, h2.
            discriminate.
    Qed.
  End tnum_sub_optimality.
End linux_tnum_subtraction.
