# Template copied from https://github.com/rocq-prover/docker-opam-action

name: stable-rocq

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  stable-rocq-build:
    uses: ./.github/workflows/build.yml
    with:
      coq_version: '9.1.1' # Keep in sync with trirocq.opam
