# Stopped using https://github.com/rocq-prover/docker-opam-action
# because it provides an outdated dune (that doesn't support rocq
# lang), requiring workarounds.

name: CI

on:
  push:
    branches: [ 'main', 'dev' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  stable-rocq-build:
    runs-on: ubuntu-latest  # container actions require GNU/Linux
    container:
      image: rocq/rocq-prover:9.2
      options: --user root # otherwise checkout fails
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dune build
        #shell: bash --login {0} # without ~/.profile, `dune` is not found
        # Even with the above, I have incorrect $PATH. So pasting the
        # $PATH found inside `docker run -it rocq/rocq-prover:9.2`
        run: PATH=/home/rocq/.opam/4.14.2+flambda/bin:/home/rocq/.local/bin:/home/rocq/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games dune build
