# Stopped using https://github.com/rocq-prover/docker-opam-action
# because it provides an outdated dune (that doesn't support rocq
# lang), requiring workarounds.

name: CI

on:
  push:
    branches: [ 'main', 'dev' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  stable-rocq-build:
    runs-on: ubuntu-latest  # container actions require GNU/Linux
    container:
      image: rocq/rocq-prover:9.1
      options: --user root # otherwise checkout fails
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dune build
        run: |
          whoami
          pwd
          chown -R rocq:rocq .
          su -s /bin/bash rocq -c 'whoami; pwd; source ~/.profile && cd /__w/trirocq/trirocq && opam install . --deps-only -y && dune build'
